version: "3.7"

services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
          - db
      ports:
          - "10002:80"
      environment:
          MYSQL_ROOT_PASSWORD: root
          PMA_HOST: db
